version: "3.7"


services:
    # We want this docker container to run an RStudio instance
    rstudio: 
        build: .
        # Tag the built Dockerfile this name
        image: akemberling/wet_feet
        # Ports, not entirely sure what this does?
        ports: 
            - "8787:8787"
        # Mapping the connections between things on our local system to the docker container
        #volumes:
        #    - ./R:/home/R
        #    - ./data:/home/data